### ISSUE TITLE
LOA Saying the Request has already been responded to.

### ISSUE THREAD

**Issue by DiscordMax** [tridentdiscord/bugs#10]
**Discord User ID:** 493081244792520714
**Guild ID Affected:** 881570702975713300
**Module/Command Affected:** LOA System

A detailed description of the bug.
When I go to deny a Request it comes up with a ephemeral message that says 'This Leave of Absence has already been responded to.' When no one has responded to it.
**Actual Result:** Not allowing me to deny the leave request.

A detailed description of what actually happened.
Ephemeral message response that says 'This Leave of Absence has already been responded to.' When no one has responded to it.
**Expected Result:**Allow me to Deny the Leave Request.

A detailed description of what you expected to happen.
I expected to be able to give a reason as to why the LOA request was denied/deny the request. 
**Reproduction Steps:**
1. Create a Leave Request
2. Press deny 

**Screenshot(s) or Video(s):**

If applicable, attach screenshot(s) or video(s) to show the bug.
[image.png](https://cdn.discordapp.com/attachments/881573566951333929/1077041717649342554/image.png)

**Comment by Flqsh** [comment]
Archived
