### ISSUE TITLE
LOA Request Random Reason.

### ISSUE THREAD

**Issue by DiscordMax** [tridentdiscord/bugs#11]
**Discord User ID:** 493081244792520714
**Guild ID Affected:** 881570702975713300
**Module/Command Affected:** LOA System

A detailed description of the bug.
So basically I press the deny button, fill up the modal with whatever I want, 
**Actual Result:** LOA gets denied with random reasoning, and says I denied it.

A detailed description of what actually happened.
I went to deny the leave request, clicked out of it (clicked the 'X') and pressed deny again and It got denied with some totally random reasoning (no modal showed the second time I clicked deny).
**Expected Result:** Modal to re open and allow me to submit a real reason.

A detailed description of what you expected to happen.
I expected to be able to close the modal and reopen it to add more to my reasoning. Also, I expected it to give an actual reason instead of same random reason I did not type nor seen before.
**Reproduction Steps:**
1. Press Deny on a Leave Request
2. Close out by pressing 'X'
3. Press Deny again

**Screenshot(s) or Video(s):**

If applicable, attach screenshot(s) or video(s) to show the bug.
[IMG_8074.png](https://cdn.discordapp.com/attachments/1039345269638185070/1077035402155798528/IMG_8074.png)
[Me attempting to re create that one above^](https://cdn.discordapp.com/attachments/881573566951333929/1077047351472041984/image.png)

**Comment by Flqsh** [comment]
Archived
