### ISSUE TITLE
In-game logging not working properly

### ISSUE THREAD

**Issue by Shluffy** [tridentdiscord/bugs#12]
**Discord User ID:** 895298316315811840
**Guild ID Affected:** 822491206231261225
**Module/Command Affected:** In-game logging

When a staff member runs the :logs command with the correct formatting trident will not log it in game logs properly

**Actual Result:**

It just got ignored, no reactions to the :logs command log

**Expected Result:**

For it to log in the game logs channel like all the others, if not to at least react to it

**Reproduction Steps:**
1.  Not sure, it seems to happen randomly
2.

**Screenshot(s) or Video(s):**

N/A

**Comment by Flqsh** [comment]
Archived
