### ISSUE TITLE
LOA Accept/Deny Error

### ISSUE THREAD

**Issue by funkzx** [tridentdiscord/bugs#13]
**Discord User ID:** 697261413764300820
**Guild ID Affected:** 792338590323572768
**Module/Command Affected:** LOA 

When I try to accept/deny a certain LOA it says "This Leave of Absence has already been responded to" but it is still pending there and un-able to be accepted. 

**Actual Result:** 

Will not let me accept or deny this certain LOA request.

**Expected Result:**

For me to be able to accept or deny the LOA.

**Reproduction Steps:**
1. This hasn't happened before just this one time
2.

**Screenshot(s) or Video(s):**

https://cdn.discordapp.com/attachments/914359254562000916/1084799668963262505/image.png

**Comment by Flqsh** [comment]
Their LoA was deleted.
