### ISSUE TITLE
Moderation button lable mismatch from the actual feature.

### ISSUE THREAD

**Issue by Salvi0** [tridentdiscord/bugs#14]
**Discord User ID:** 1054541801417093181
**Guild ID Affected:** 1067576438334689280
**Module/Command Affected:** Moderation

A detailed description of the bug.

**Actual Result:** When the Moderate Confirm button in the moderation settings is disabled, it actually ask you to approve moderation actions (this also show that the settings is turned on inside the server config). Differently the when the button says it's enabled, it completely skip the pending action (in this case inside the server settings the option appear to be disabled.)

A detailed description of what actually happened.

**Expected Result:** basically when the button says the confirm moderation is disabled it should skip the pending action and vice versa.

A detailed description of what you expected to happen.

**Reproduction Steps:**
1. Type /config then activate the moderation module and return to the main menu. After, modify the moderation module and enable/disable the confirm moderation action.
2. Try to moderate someone and if the button is set to disable the bot will pormpt you to approve/deny the moderation, vice versa if the button is on enabled.

**Screenshot(s) or Video(s):**
![image](https://user-images.githubusercontent.com/66015217/229348428-21e07c0f-8134-4873-a9fe-37f418fea19e.png)

If applicable, attach screenshot(s) or video(s) to show the bug.

**Comment by Flqsh** [comment]
Resolved: Fix a while ago.
