### ISSUE TITLE
Info Command Invalid Link

### ISSUE THREAD

**Issue by ChefPizzaCodes** [tridentdiscord/bugs#16]
**Discord User ID:** 1096636495835705417
**Guild ID Affected:** 1039315801972424765
**Module/Command Affected:** `/info`

A detailed description of the bug.
In the embed sent after running the command `/info`, it gave me an invalid link to the support server.

**Actual Result:**
A detailed description of what actually happened.
The link provided was invalid.

**Expected Result:**
A detailed description of what you expected to happen.
I expected to be redirected to the Trident support server.

**Reproduction Steps:**
1. Run the command `/info`.
2. Press the hyperlink "Support".

**Screenshot(s) or Video(s):**
https://github.com/tridentdiscord/bugs/assets/131921419/9d5e30ed-fe13-4dee-ba56-78f6f7c49e48

**Comment by whoissound** [comment]
Fixed
