### ISSUE TITLE
Support Command Invalid Invite

### ISSUE THREAD

**Issue by ChefPizzaCodes** [tridentdiscord/bugs#17]
**Discord User ID:** 1096636495835705417
**Guild ID Affected:** 1039315801972424765
**Module/Command Affected:** `/support`

A detailed description of the bug.
When running the command `/support`, I was provided with an invalid link to the Trident support server.

**Actual Result:**
When pressing the button that should redirect me to the Trident support server, I was given an invalid invite.

**Expected Result:**
I expected to be redirected to the Trident support server via discord.gg/trident.

**Reproduction Steps:**
1. Run the command `/support`.
2. Press the button provided.

**Screenshot(s) or Video(s):**
https://github.com/tridentdiscord/bugs/assets/131921419/ff7c4c34-4fa8-4082-9991-4425ecde5f4e

**Comment by whoissound** [comment]
Fixed
