### ISSUE TITLE
Help Command Invalid Link

### ISSUE THREAD

**Issue by ChefPizzaCodes** [tridentdiscord/bugs#18]
**Discord User ID:** 1096636495835705417
**Guild ID Affected:** 1039315801972424765
**Module/Command Affected:** `/help`

**A detailed description of the bug.**
When running the command `/help`, I was provided with an invalid link to the Trident support server.

**Actual Result:**
When pressing the hyperlink that should redirect me to the Trident support server, I was given an invalid invite.

**Expected Result:**
I expected to be redirected to the Trident support server via discord.gg/trident.

**Screenshot(s) or Video(s):**
https://github.com/tridentdiscord/bugs/assets/131921419/fa2f1ad1-dfcd-4a25-9fb8-9947ca9e6414

**Comment by whoissound** [comment]
Fixed
