### ISSUE TITLE
In-Game Logging Feature Available

### ISSUE THREAD

**Issue by ChefPizzaCodes** [tridentdiscord/bugs#19]
**Discord User ID:** 1096636495835705417
**Guild ID Affected:** 1039315801972424765
**Module/Command Affected:** `/config`

**A detailed description of the bug:**
The "In-Game Logging" feature is still an option when enabling or disabling modules, even though this feature is no longer compatible and will most likely never return.

**Reproduction Steps:**
1. `/config`
2. Enable or Disable Module < In-Game Logging 

**Screenshot(s) or Video(s):**
https://github.com/tridentdiscord/bugs/assets/131921419/6a4025d0-c49c-4bfe-950d-60fad601cd31

**Comment by whoissound** [comment]
Not a bug
