### ISSUE TITLE
LOA "Approved By:"

### ISSUE THREAD

**Issue by CupCake8061** [tridentdiscord/bugs#2]
**Discord User ID:** 815916279965024296
**Guild ID Affected:** 817607800954945567
**Module/Command Affected:** LOA

A detailed description of the bug. 
The "Approved By:" At the end of an LOA (Not ending early) always mentions the user that is on LOA, not who approved it.

**Actual Result:**
Wrong Mention For Approval

A detailed description of what actually happened.
Wrong mention on ending of LOA "Approved By: <Person on LOA, Not the Approver>"
**Expected Result:**
Person who approved it's mention

A detailed description of what you expected to happen.
The right mention.
**Reproduction Steps:**
1. 
2.

**Screenshot(s) or Video(s):**

If applicable, attach screensh
<img width="418" alt="Screen Shot 2023-01-28 at 9 38 14 am" src="https://user-images.githubusercontent.com/123785461/215234674-17b67b83-c059-499f-bfca-0fab52cc3a9c.png">
ot(s) or video(s) to show the bug.

**Comment by CupCake8061** [comment]
I would add more examples, but i can't due to... privacy.

**Comment by Flqsh** [comment]
This has been fixed.
