### ISSUE TITLE
LOA Manage not working correctly 

### ISSUE THREAD

**Issue by Donosolo** [tridentdiscord/bugs#20]
**Discord User ID:** 927308229271232522
**Guild ID Affected:**
**Module/Command Affected:** LOA Manage

A detailed description of the bug.

**Actual Result:** It’s not allowing me to extend or delete my leave. I am on a LOA and it says I’m not in it. 

A detailed description of what actually happened.

**Expected Result:** I did leave manage and it says I’m not on leave but I am. I’m trying to extend my leave but it’s not allowing me to.

A detailed description of what you expected to happen.

**Reproduction Steps:**
1. /leave manage 
2. Then extend my request

**Screenshot(s) or Video(s):**
![8332BDBC-1F5B-4173-9B94-86CFF606E57B](https://github.com/tridentdiscord/bugs/assets/136028976/a1e53669-59a7-4a9b-804a-b7147a461fb0)

If applicable, attach screenshot(s) or video(s) to show the bug.

**Comment by Flqsh** [comment]
Not a bug, an admin probably ended your leave. Recreate bug report if it reoccurs.
