### ISSUE TITLE
/activity view not responding

### ISSUE THREAD

**Issue by YellowMacaroni** [tridentdiscord/bugs#21]
**Discord User ID:** N/A
**Guild ID Affected:** All (tested on 884351371095203850)
**Module/Command Affected:** Shifts

When using `/activity view`, (when an invalid/too large duration is given) the application does not respond.

**Actual Result:**

The application does not respond.

**Expected Result:**

The bot returns a list of shift data from within the duration for the given requirement.

**Reproduction Steps:**
1. Run `/activity view` with a large / erroneous value such as `1000d`, `0`, etc.
2. Wait

**Screenshot(s) or Video(s):**
![Screenshot 2023-06-09 190428](https://github.com/tridentdiscord/bugs/assets/92680766/18a9ca4f-dde1-425b-9532-8fc394dd0253)
![Screenshot 2023-06-09 190403](https://github.com/tridentdiscord/bugs/assets/92680766/46b14291-3eb0-4137-92dc-15ab34094ef3)

**Comment by Flqsh** [comment]
Closed: Cannot reproduce, sends proper error message of "Duration must be between 12 hours and 1 year.", probably already fixed.
