### ISSUE TITLE
/shift admin remove time

### ISSUE THREAD

**Issue by YellowMacaroni** [tridentdiscord/bugs#22]
**Discord User ID:** All
**Guild ID Affected:** All
**Module/Command Affected:** Shifts (/shift admin)

When removing time from a user, after selecting how much time you want to remove, it just defers the reply forever after editing the original message. **I am unsure if this also happens with other functions (add time, delete, etc.).**

**Actual Result:**

Interaction is deferred forever.

**Expected Result:**

The reply is edited or deleted.

**Reproduction Steps:**
1. /shift admin (user)
2. Select modify
3. Enter the shift ID
4. Remove a certain amount of time.

**Screenshot(s) or Video(s):**
https://github.com/tridentdiscord/bugs/assets/92680766/add62c5b-2d82-4576-adfb-6f4ce28e6c36

**Comment by Flqsh** [comment]
Closed: Works as intended (probably already fixed)
