### ISSUE TITLE
/shift types create with the name "default"

### ISSUE THREAD

**Issue by YellowMacaroni** [tridentdiscord/bugs#23]
**Discord User ID:** All
**Guild ID Affected:** All
**Module/Command Affected:** Shifts

When creating a shift type with the name "default" it displays an error "The name of the shift type must be less than 20 characters." instead of an error message related to the issue that "default" is already a shift type / cannot be used.

**Actual Result:**

When running `/shift types create name:default`, it says "The name of the shift type must be less than 20 characters."

**Expected Result:**

When running `/shift types create name:default`, it should say "You cannot create a shift type with this name." or similar.

**Reproduction Steps:**
1. Run `/shift types create name:default`.

**Screenshot(s) or Video(s):**
![image](https://github.com/tridentdiscord/bugs/assets/92680766/e4b9c401-200e-410a-ac6e-e7f31c43abb8)

**Comment by Flqsh** [comment]
Resolved: Added separate error message
