### ISSUE TITLE
Sourcebin Link Generation

### ISSUE THREAD

**Issue by finaIcutpro** [tridentdiscord/bugs#24]
**Discord User ID:** 459374864067723275
**Guild ID Affected:** 1039315801972424765
**Module/Command Affected:** /shift leaderboard

A detailed description of the bug. 

**Actual Result:** the sourcebin link doesn’t do anything, embed doesn’t update when you click the button to generate one

A detailed description of what actually happened.

**Expected Result:** the feature to work

A detailed description of what you expected to happen.

**Reproduction Steps:**
1.  Run shift leaderboard
2. Attempt to generate a sourcebin link

**Screenshot(s) or Video(s):** https://cdn.discordapp.com/attachments/1035365916973744188/1149766297018716190/RPReplay_Final1694195878.mov

If applicable, attach screenshot(s) or video(s) to show the bug.

**Comment by Flqsh** [comment]
Resolved: Exceeds Sourceb.in's character limits when in a server with thousands of staff members. Added a response message to handle this outlier event.
