### ISSUE TITLE
Reminders does not ping roles

### ISSUE THREAD

**Issue by YellowMacaroni** [tridentdiscord/bugs#25]
**Discord User ID:** All
**Guild ID Affected:** All? (Tested in 884351371095203850 and reported https://discord.com/channels/1039315801972424765/1039345269638185070/1150171123602948296)
**Module/Command Affected:** Reminders

The reminders do not ping roles when sent, it just sends the mention without pinging the users.

**Actual Result:**

No ping.

**Expected Result:**

Pings the users.

**Reproduction Steps:**
1. Create a reminder.
2. Give yourself the role that the reminder pings.
3. Wait.

**Screenshot(s) or Video(s):**
![image](https://github.com/tridentdiscord/bugs/assets/92680766/0c3b05bb-90f9-40da-83a9-03b8cb68e8cd)
https://cdn.discordapp.com/attachments/1039345269638185070/1150172210615558196/Screen_Recording_20230909_135324.mp4

**Comment by Flqsh** [comment]
Resolved: Fixed
