### ISSUE TITLE
Points module doesn't have a 'Save Channels' or 'Back' button.

### ISSUE THREAD

**Issue by FFlatduck** [tridentdiscord/bugs#26]
**Discord User ID:**
**Guild ID Affected:**
**Module/Command Affected:**

A detailed description of the bug.

**Actual Result:**

A detailed description of what actually happened.

**Expected Result:**

A detailed description of what you expected to happen.

**Reproduction Steps:**
1. 
2.

**Screenshot(s) or Video(s):**

If applicable, attach screenshot(s) or video(s) to show the bug.

**Comment by Flqsh** [comment]
Will add the back button back. The no save button is intention, just click off of the select menu to save.
