### ISSUE TITLE
Points module doesn't have a 'Save Channels & Roles' or 'Back' button.

### ISSUE THREAD

**Issue by FFlatduck** [tridentdiscord/bugs#27]
**Discord User ID:** 527934704389980160
**Guild ID Affected:** All
**Module/Command Affected:** Points

When using `/config` > Points you'll notice there is no back button and more importantly a button to save channels and roles you've set in the dropdown menus.

**Actual Result:** Channels & Roles don't save.

**Expected Result:** Channels & Roles should save (with Save Channels & Roles button). 

**Reproduction Steps:**
1. /config
2. Points Module
3. Use your eyes.

**Screenshot(s) or Video(s):**

If applicable, attach screenshot(s) or video(s) to show the bug.
![image](https://github.com/tridentdiscord/bugs/assets/128323609/5b7ba41f-b7ac-461c-91b1-961ad3ac0080)

**Comment by Flqsh** [comment]
Duplicate
