### ISSUE TITLE
Failed Interaction when using the /info slash command.

### ISSUE THREAD

**Issue by Dymidless** [tridentdiscord/bugs#29]
**Discord User ID:** 749895975694499930
**Guild ID Affected:** 1039187884403601498, 1039315801972424765 and probably all servers.
**Module/Command Affected:** /info Slash Command

The bug occurs when using the /info slash command. The first attempt results in an _Interaction failed_ response. However, if you quickly use the command again, it works as expected. This inconsistent behavior leads to confusion, requiring an additional command execution for the desired outcome.

**Actual Result:**

Upon executing the /info command, the bot responds with _Interaction failed_. However, if the command is used again within a short period, it functions correctly.

**Expected Result:**

It is expected that using the /info command should prompt the bot to respond with the relevant information without interaction errors.

**Reproduction Steps:**
1. Execute the /info slash command
2. Observe the _interaction failed_ response.
3. Re-execute the /info slash command within a short timeframe.
4. Verify that the command functions correctly on the second attempt.

**Screenshot(s) or Video(s):**

https://i.imgur.com/0jSZQOM.png
![tridentbugreport](https://github.com/tridentdiscord/bugs/assets/83553548/7cfb463a-6636-48ee-b779-55a2c2f4f828)

**Comment by LostBreezely** [comment]
Had some free time on my hands, sorry I initially forgot about this.
It has been promptly **resolved**. <3

**Comment by Dymidless** [comment]
Thank you ♥️

**Comment by LostBreezely** [comment]
Fixed `/info` command response erroring/timing out.

**Comment by LostBreezely** [comment]
Fixed /info command response erroring/timing out.

**Comment by LostBreezely** [comment]
Bruh

**Comment by LostBreezely** [comment]
Fixed `/info` command response erroring/timing out.

**Comment by LostBreezely** [comment]
Didn't mean to re-open that. <3
