### ISSUE TITLE
Error when Editing Shift while On Break

### ISSUE THREAD

**Issue by whoissound** [tridentdiscord/bugs#3]
**Discord User ID:** 817570274932424715
**Guild ID Affected:** N/A
**Module/Command Affected:** Shift Management Module

When running `/shift admin` and deleting the shift of a user currently on break and then when the user tries to go off break, it returns with a "This interaction failed" error.

**Reproduction Steps:**
1. Create a shift and go on break.
2. Run `/shift admin` and delete the shift.
3. Attempt to go off break or interact with the `/shift manage` command.

**Screenshot(s) or Video(s):**

If applicable, attach screenshot(s) or video(s) to show the bug.

**Comment by Flqsh** [comment]
Cannot be reproduced.
