### ISSUE TITLE
Invalid invitation link in tag $ts

### ISSUE THREAD

**Issue by Dymidless** [tridentdiscord/bugs#30]
**Discord User ID:** 749895975694499930
![trident](https://github.com/tridentdiscord/bugs/assets/83553548/289e4a17-67f6-45a8-9435-5ef1ced44429)

**Guild ID Affected:** 1039315801972424765 (Only server where the tag exists I think)
**Module/Command Affected:** $ts command from Trident Support Bot

The invitation link to the Trident survial Discord server in the button displayed when using the $ts command is invalid 

**Actual Result:**

The invitation link to the Trident survial Discord server in the button displayed when using the $ts command is invalid

**Expected Result:**

That the invitation link is valid  

**Reproduction Steps:**
1. Using the $ts command from the Trident Support bot 
2. Click on the **Join Trident Survial** button

**Screenshot(s) or Video(s):**

**Comment by LostBreezely** [comment]
We'll just remove the button and prompt entirely. I'll do it when I'm available. Doing this on git mobile rn.

**Comment by LostBreezely** [comment]
Button and prompt have been removed. <3
