### ISSUE TITLE
Trident DM slash commands issue

### ISSUE THREAD

**Issue by xInfinitxy0** [tridentdiscord/bugs#31]
**Discord User ID:** 763388195261644811
**Guild ID Affected:** No guild is affected. This bug affects all users via DMs.
**Module/Command Affected:**  Trident DM slash commands.

When going to Trident's direct messages and attempting to run any of the slash commands available there you receive the "This application did not respond. This bug affects all of the commands available. /ping, /support, /invite, /info, and /help. 

**Actual Result:**
Trident responds with the "This application did not respond" error when running the commands in Trident's direct messages.

**Expected Result:**
Trident is supposed to respond to the slash commands successfully without any error or complication. The commands /ping, /support, /invite, /info, and /help should all work in direct messages with Trident.

**Reproduction Steps:**
1. Go to Trident#5458's direct messages.
2. Attempt to run any slash commands from Trident. (/ping, /support, /invite, /info, and /help)

**Screenshot(s) or Video(s):**
![Screenshot 2023-10-14 6 31 05 PM](https://github.com/tridentdiscord/bugs/assets/146041624/60e861e6-d2b5-42ff-8824-c35519f0bf83)

**Comment by LostBreezely** [comment]
**Deployed Fix.**

**Comment by LostBreezely** [comment]
After some slight tweaking, the above issue has been promptly resolved, you should now be able to run commands within DMs. (Utility commands for the most part)

Obviously this doesn't include all commands but you don't need me to explain that.
Commands that are intended to be run in DMs can now be run in DMs without issue.

**Thanks Infinity! <3**

**Comment by LostBreezely** [comment]
Apparently I'm an idiot and I didn't push everything, whilst the commands work they don't respond as intended.
Bare with me for 5 minutes.

**Comment by LostBreezely** [comment]
My apologies, I was adjusting my version of the bot earlier and in doing so didn't push the entirety as I had another dev version.

Long story short, I've pushed the command adjustments to allow for use in DMs.
NOW, everything should work fine. 

`/info` --> Changed color so it's not dependent on a role color to provide support for DMs. 
`/support` --> Empheral set to false in DMs.
`/ping` --> had Cluster and Shard respond as `N/A `if ran in DMs.
