### ISSUE TITLE
Delete Moderation Context Menu 

### ISSUE THREAD

**Issue by xInfinitxy0** [tridentdiscord/bugs#32]
**Discord User ID:** 763388195261644811
**Guild ID Affected:** All guilds.
**Module/Command Affected:** "Delete Moderation"  context menu option.

When using the "Delete Moderation" context menu option Trident does not send an embedded message informing the user that the action was successfully completed. Instead Trident responds with "This application didn't respond"

**Actual Result:**
After using the "Delete Moderation" context menu and Trident successfully removing the moderation it responds with "This application didn't respond" and no embedded message was sent to inform the user the moderation was deleted.

**Expected Result:**
After using the "Delete Moderation" context menu an ephemeral embedded message would appear after the moderation was successfully deleted telling the user that the moderation was successfully deleted.

**Reproduction Steps:**
1. Use the `/moderate` command
2. Use the "Delete Moderation" context menu

**Screenshot(s) or Video(s):**
![image](https://github.com/tridentdiscord/bugs/assets/146041624/824ae4f0-784c-4872-b8a6-915a5cdcdcd8)

**Comment by LostBreezely** [comment]
Heya Infinity.
I've gone ahead and adjusted the options reply on the context menu, everything should work perfectly fine now.

I've looked in to the `editModeration` option as well, you'll find it occasionally errors but will work if run again. 
This will be fixed ASAP, same goes for error responses which weren't triggering.

**Comment by LostBreezely** [comment]
Resolved, +deferred response.

**Comment by LostBreezely** [comment]
Turns out ASAP is now.
Resolved +undeferred response however drastically decreased response time to prevent timeouts.
Optimized both, including `Edit Moderation`.

`Edit Moderation` and `Delete Moderation` have both been optimized and work flawlessly without error.

**Comment by LostBreezely** [comment]
🎄

**Comment by Flqsh** [comment]
🦇

**Comment by xInfinitxy0** [comment]
Thank you Breezely. I was going to report the editModeration issue as well but couldn't find solid reproducing steps. Spectacular ✨
