### ISSUE TITLE
/shift types create character limit

### ISSUE THREAD

**Issue by xInfinitxy0** [tridentdiscord/bugs#33]
**Discord User ID:** 763388195261644811
**Guild ID Affected:** All guilds.
**Module/Command Affected:** `/shift types create` command

When using the `/shift types create` command under the "Name" argument a Discord error is given when trying to enter 30 or more characters into that one argument. When actually running the command you get an embed error saying that the max amount of characters is 20 for the shift type name.

**Actual Result:**
Being unable to make my shift type name 21-30 characters. This caused me to have to create the name with 20 characters.

**Expected Result:**
Being able to create a shift type name with 21-30 characters (as promised by the "Name" argument error).

**Reproduction Steps:**
1.  Run the /shift types create command
2. Enter more than 30 characters (observe that error)
3. Enter 21-30 characters and send the command (observe the conflicting information)

**Screenshot(s) or Video(s):**
![Screenshot 2023-10-21 6 47 07 PM](https://github.com/tridentdiscord/bugs/assets/146041624/15e454c8-826f-4093-83a7-91396ca86101)
![Screenshot 2023-10-21 6 46 56 PM](https://github.com/tridentdiscord/bugs/assets/146041624/3651a15a-577f-4eb2-a076-13344a8f7f3d)

**Comment by LostBreezely** [comment]
Thanks again Infinity, the above issue has been resolved.

The above has been adjusted, the character limit has been raised to 30.
This means you should never see the response "The name of the shift type must be less than 30 characters" as the 30 character limit should prevent that and the command from being excecated. 

Character limit is 30, the string entered must be > 30.

**Comment by LostBreezely** [comment]
Character limit updated > 30 for `Shift Types Create`.
