### ISSUE TITLE
/ping command cluster N/A

### ISSUE THREAD

**Issue by xInfinitxy0** [tridentdiscord/bugs#34]
**Discord User ID:** 763388195261644811
**Guild ID Affected:** 1008212515345416282 & 1147931649380728985 (I would imagine more guilds are affected.)
**Module/Command Affected:** `/ping` command

The `/ping` command shows "N/A" as the cluster for specific guilds. This bug only affects specific guilds so reproduction of this might be difficult. 

**Actual Result:**
The cluster displays as "N/A" when running `/ping` to find out the cluster your guild is on.

**Expected Result:**
The cluster would display what number cluster the guild is on and not display "N/A" for the cluster.

**Reproduction Steps:**
1.  Run the `/ping` command.
2. Observe the results.

**Screenshot(s) or Video(s):**
![Screenshot 2023-10-21 9 22 18 PM](https://github.com/tridentdiscord/bugs/assets/146041624/fc8f0e2b-0efb-4a7d-aacb-94572806bcea)
![Screenshot 2023-10-21 9 21 58 PM](https://github.com/tridentdiscord/bugs/assets/146041624/69425f57-87a1-4824-a368-dc60c941a98e)

**Comment by Flqsh** [comment]
This issue has been resolved.
