### ISSUE TITLE
Hyperlink in Kick/Ban Log Webhook Channel's embed not appearing correctly.

### ISSUE THREAD

**Issue by luuwyd** [tridentdiscord/bugs#35]
**Discord User ID:** 416675699038879755
**Guild ID Affected:** 1104829884511047841
**Module/Command Affected:** Moderations Module (Kick/Ban Log Webhook Channel)

When a moderator in-game completes a ban request by doing `:ban (User ID)` and if you have the webhook logging channel setup with Trident configuration, it should log in the channel you selected, it does, however, the hyperlink that should direct to the ban request that was requested and the moderation log.

**Actual Result:**
The hyperlink in the Kick/Ban Log Webhook Channel embed appears to be bugged and does not appear correctly when someone completes a ban request.

**Expected Result:**
The hyperlink in the Kick/Ban Log Webhook Channel should be clickable and then direct them to the ban request that was requested and the moderation log.

**Reproduction Steps:**
1. Request a ban request by filling out anything into the empty boxes, such as: `/banrequest add user:Roblox reason:LTAP`
2. Get a moderator in-game to ban the user by their Roblox User ID, such as: `/ban 1`
3. If they have their Roblox account linked with Trident, it should log in the Kick/Ban Log Webhook Channel) you selected.
4. The embed does not show the hyperlink that would direct them to the ban request that was requested and the moderation log.

**Screenshot(s) or Video(s):**
![wrongresult](https://github.com/tridentdiscord/bugs/assets/73377543/8a33341a-75e9-453e-a18c-d7be7b1706a3)

**Comment by LostBreezely** [comment]
Thank you for reporting this c4relove. 
I've gone ahead and adjusted the way the link is generated. (Even though it wasn't even generating a link the first time around)
`Moderation` and `Ban Request` will both hyperlink and take you to their respective messages.

Everything should work just fine now. 👍

**Comment by LostBreezely** [comment]
Adjusted the way the link is generated.
