### ISSUE TITLE
Sourcebin Link Generation

### ISSUE THREAD

**Issue by xInfinitxy0** [tridentdiscord/bugs#36]
**Discord User ID:** 763388195261644811
**Guild ID Affected:** 1039315801972424765 (Trident support & other big guilds)
**Module/Command Affected:** `/shift leaderboard` command

When running the `/shift leaderboard` command and clicking the "Raw Data" button and then the "Generate Sourcebin Link" button it doesn't seem to work 100% of the time. When clicking the button  nothing happens. No errors are provided or anything.

**Actual Result:**
Trident does not generate a sourcebin link as requested and the button does nothing. No error message is provided upon clicking the button either.

**Expected Result:**
Trident to generate the sourcebin link as requested.

**Reproduction Steps:**
1. Find a guild with a large number of staff members (Trident Support as an example)
2. Run `/shift leaderboard
3. Click "Raw Data"
4. Click "Generate Sourcebin Link" 

**Screenshot(s) or Video(s):**
[Video](https://github.com/tridentdiscord/bugs/assets/146041624/38dcdc95-0224-471d-a440-683e01f67f14)

**Comment by xInfinitxy0** [comment]
For your information: It is not near the sourcebin character limit so there's no reason why it shouldn't be able to generate the sourcebin link. I'm able to create a sourcebin with the same information myself (same formatting and text), but Trident cannot.

**Comment by Flqsh** [comment]
This is now fixed. The problem originated with an improperly configured error message for when the content of the sourcebin exceeds 50,000 characters. Thanks for the report, apologizes for the extreme delay.
