### ISSUE TITLE
Sourcebin Generation Error Message

### ISSUE THREAD

**Issue by xInfinitxy0** [tridentdiscord/bugs#37]
**Discord User ID:** 763388195261644811
**Guild ID Affected:** 1039315801972424765 (Trident Support and other big guilds)
**Module/Command Affected:** /shift leaderboard
 
 The error message provided when the leaderboard is over 50,000 characters is inaccurate. The leaderboard character count was 49359 based on the text file that Trident provided to me. In addition the character limit for sourcebin doesn't seem to be 50,000 as of right now. I'm able to create a sourcebin with more than 50,000 characters.
  

**Actual Result:**
Trident errors with the following error message "The leaderboard is too large to generate a link for.
Exceeds character limit of 50,000." when it does not exceed the character limit.

**Expected Result:**
Trident to not give that error and generate the sourcebin link.

**Reproduction Steps:**
This error message is incredibly difficult to reproduce now that I'm trying to reproduce the issue. I've provided a screenshot below of the issue.
1. Run the /shift leaderboard (guild tested in had 49359 characters as the leaderboard)
2. Click "Raw Data"
3. Click "Generate Sourcebin Link" 

**Screenshot(s) or Video(s):**
![Screenshot](https://github.com/tridentdiscord/bugs/assets/146041624/253744a8-96d3-4d86-819d-d827d48f5319)

**Comment by xInfinitxy0** [comment]
I couldn't reproduce this a 2nd time because now the generate sourcebin link doesn't work at all for this guild. Another bug report was already submitted regarding that issue.

**Comment by Flqsh** [comment]
I've upped the character limit to 150k characters
