### ISSUE TITLE
Delete moderation context menu error

### ISSUE THREAD

**Issue by xInfinitxy0** [tridentdiscord/bugs#38]
**Discord User ID:** 763388195261644811
**Guild ID Affected:** All guilds.
**Module/Command Affected:** "Delete moderation" context menu

The delete moderation context menu option doesn't give out a descriptive error when attempting to use the option on a message which has no punishment data. Trident displays the "Something unexpected went on" error when trying to use the option on a message which has no punishment data.

**Actual Result:**
Trident displaying "Something went wrong" when attempting to use the delete moderation context menu.

**Expected Result:**
Trident to display the "No punishment data was found for this message." for this message error just like the edit moderation context menu option.

**Reproduction Steps:**
1. Use the delete moderation context menu option on an invalid message.

**Screenshot(s) or Video(s):**
![Bug Report Screenshot](https://github.com/tridentdiscord/bugs/assets/146041624/45fb9570-b153-46e2-924a-7b3a9715d3ba)

**Comment by Flqsh** [comment]
This has been fixed. Thanks for the report & apologies for the delay
