### ISSUE TITLE
Set punishment options reset not working

### ISSUE THREAD

**Issue by xInfinitxy0** [tridentdiscord/bugs#39]
**Discord User ID:** 763388195261644811
**Guild ID Affected:** 1170378567796936834 (and all guilds)
**Module/Command Affected:** "Set punishment options" configuration option // `/moderate `command

When removing all of your punishment options Trident is supposed to reset back to default settings such as ban, kick, verbal warnings, and warning. However, when removing everything from the "Set punishment options" menu it does not reset to default settings. 

**Actual Result:**
Trident says "Set one punishment options: ``" after removing everything from the "Set punishment options" menu when it's supposed to reset to the default punishment options, which it does not do.

**Expected Result:**
Trident to reset the punishment options and go back to the default settings (ban, kick, verbal warning, and warning).

**Reproduction Steps:**
1.  Set a punishment option.
2.  Remove the punishment option.
3.  Observe the results.

**Screenshot(s) or Video(s):**
![Screenshot 1](https://github.com/tridentdiscord/bugs/assets/146041624/8fbb24d6-e08f-41e3-9d3c-52e63436ba59)
![Screenshot 2](https://github.com/tridentdiscord/bugs/assets/146041624/c7f7467c-1680-445b-bc8e-5524eadb7bf7)
![Screenshot 3](https://github.com/tridentdiscord/bugs/assets/146041624/4b8bea79-2ead-403b-8e85-ca39d9ae3013)

**Comment by Flqsh** [comment]
No longer a feature -> Moved to dashboard
