### ISSUE TITLE
Application does not respond to /moderations

### ISSUE THREAD

**Issue by NoSkillDevelopment** [tridentdiscord/bugs#4]
**Discord User ID:** 842211153957486672
**Guild ID Affected:** 1047051143936737330, also confirmed by other users
**Module/Command Affected:** /moderations

Upon running the /moderations command, it gives a response stating "The application did not respond".

**Actual Result:**

The application does not respond to the command, at least not within the time allowed by Discord.

**Expected Result:**

It should show a list of moderations for the user, as intended.

**Reproduction Steps:**
1. Go into a server where you have permission to view moderations
2. Run /moderations on any user

**Screenshot(s) or Video(s):**

![image](https://user-images.githubusercontent.com/109725210/215380523-c08021ce-0170-40a1-b5bc-e9d1f32f87e6.png)

**Comment by Flqsh** [comment]
This is now fixed.
