### ISSUE TITLE
/activity view not working with shift types

### ISSUE THREAD

**Issue by YellowMacaroni** [tridentdiscord/bugs#43]
**Discord User ID:** All?
**Guild ID Affected:** All? (Tested in 1075927208981430422)
**Module/Command Affected:** Activity (/activity view)

When running the `/activity view` command and using a shift type in the `shift-type` option, the bot will not respond to the command and instead will just defer and then not respond.

**Actual Result:**
No report sent when running the `/activity view` command with a shift type.

**Expected Result:**
A report is sent when running the `/activity view` command as it should do without a shift type.

**Reproduction Steps:**
1. Run `/activity view` with a shift type.

**Screenshot(s) or Video(s):**
![image](https://github.com/tridentdiscord/bugs/assets/92680766/b30cc50d-a75b-49e8-8f1d-dbbfc3f1c9bb)
![image](https://github.com/tridentdiscord/bugs/assets/92680766/1aeb1f58-9e1c-48f7-9e6b-b20a6a5304f1)

**Comment by Flqsh** [comment]
Fixed recently -- Apologies for the delay.
