### ISSUE TITLE
Incorrect description of the /ping command

### ISSUE THREAD

**Issue by Dymidless** [tridentdiscord/bugs#44]
**Discord User ID:** All?
**Guild ID Affected:** All? (Tested in 1039315801972424765)
**Module/Command Affected:** /ping slash command

When you use the Slash command /ping, you see that the description for it is "Check ping and uptime", but the bot's uptime is actually not shown anywhere when using the command. 

**Actual Result:**

The command description says that it also shows the uptime, but it doesn't.

**Expected Result:**

That in the description of the command it only shows that it is used to see the shard's ping or that the uptime is also shown when using it. 

**Reproduction Steps:**
1. Write to a server that has Trident /ping
2.Read the command description 
3. Run the command 

**Screenshot(s) or Video(s):**
![IMG_20240119_074201](https://github.com/tridentdiscord/bugs/assets/83553548/370782b6-9015-4ed6-a92f-614cd2d9e101)

**Comment by Flqsh** [comment]
The command description has been updated. Thank you for the report & apologies for the delay.
