### ISSUE TITLE
Activity Tracking does not save on dashboard.

### ISSUE THREAD

**Issue by FFlatduck** [tridentdiscord/bugs#45]
**Discord User ID:** 527934704389980160
**Module/Command Affected:** Activity Tracking
**Browser:** Google Chrome
**Operating System:** Windows 11

On Trident's dashboard, in the Activity Tracking module the first three fields (Frequency, Duration, and Shift Requirement) do not save. There is no prompt to "Apply" the changes and other work arounds dont work. For example, disabling "Include Management", then saving from there still doesn't save the other fields.

**Actual Result:** Activity Tracking does not save. There is no prompt to "Apply" changes.

**Expected Result:** Prompt to "Apply" changes should appear once any part of the module is edited, and should save.

**Reproduction Steps:**
1. Go to your dashboard.
2. Go to the Activity Tracking module.
3. Edit any of the first three fields - no "Apply" changes prompt will appear.
4. Refresh - the fields will reset to 0, 0, 0. No changes are saved.

**Screenshot(s) or Video(s):**
![image](https://github.com/tridentdiscord/bugs/assets/128323609/33fe412f-d825-4432-8fa0-1b7a724a9df6)
If applicable, attach screenshot(s) or video(s) to show the bug.

**Comment by Flqsh** [comment]
This was fixed some time ago. Apologies for the delay in closing.
