### ISSUE TITLE
Dashboard not working

### ISSUE THREAD

**Issue by bruxvux** [tridentdiscord/bugs#49]
**Discord User ID:** bruxvux
**Browser:** Google Chrome + Opera GX
**Operating System:** Android

When I try to change the role or channel for permissions or shifts it doesn't show me the list of channels or roles to select from. Also when I try to create a new permission or shift it gets deleted and all changes revoked when I press apply.

**Actual Result:**
All changes got revoked and if I tried to modify I couldn't select anything. Any roles or any channels because it said no available options.

**Expected Result:**
The changes would take place and everything would stay there.

**Reproduction Steps:**
1. Invite the bot to a server
2.Open the dashboard and try to add or modify a permissions or shifts.
3. Press apply

**Screenshot(s) or Video(s):**

https://github.com/tridentdiscord/bugs/assets/85338266/642889d9-9753-42b1-8061-f6cc2a42fc5e

**Comment by bugsbirb** [comment]
Try and log out and back in see if that works

**Comment by bruxvux** [comment]
@bugsbirt Tried that many times also tried different phones and Windows 10 computers but that doesn't work either. Does anyone else have this issue? The bot doesn't seem to see any roles and channels.

**Comment by WhispMacaroni** [comment]
We seem to be having problems with the dashboard at the moment, but it should be fixed soon.

**Comment by YellowMacaroni** [comment]
We seem to be having problems with the dashboard at the moment, but it should be fixed soon.

**Comment by Dymidless** [comment]
This issue was resolved yesterday and will be marked as completed soon.

**Comment by LostBreezely** [comment]
Thank you for the bug report "_therapist bruxvux_".
We've implemented a fix for this issue, we appreciate your patience.
