### ISSUE TITLE
Reminders, edit intervals error

### ISSUE THREAD

**Issue by skarzy123** [tridentdiscord/bugs#5]
**Discord User ID:** 603960462027128832
**Guild ID Affected:** 977043128789893131
**Module/Command Affected:** Reminders --> edit interval

A detailed description of the bug.

**Actual Result:**

When I created a reminder I went to edit the interval and I saw there was just a random letter "a" already within the message. This clutters up the menu and you can not see the message saying what to put in the section. (Screenshot at the bottem)

**Expected Result:**

I expect the edit intervals option within the reminder to not have a "a" in it once opened. This allows you to see what to add into the section and or how to.

**Reproduction Steps:**
1. /reminders create id: test (Works with any ID that I have tried)
2. "edit interval"

**Screenshot(s) or Video(s):**
![image](https://user-images.githubusercontent.com/124023260/215673361-1c66c662-25ba-485e-b8d0-6635c4b9cb3f.png)

If applicable, attach screenshot(s) or video(s) to show the bug.

**Comment by Flqsh** [comment]
This has been fixed.
