### ISSUE TITLE
Discord Server links to the wrong discord server

### ISSUE THREAD

**Issue by GamerPandaa** [tridentdiscord/bugs#50]
**Discord User ID:** 880176954630881281
**Browser:** Google Chrome
**Operating System:** Windows 11 

A detailed description of the bug.

**Actual Result:** When you click on the discord support server to join, it takes you to a (most likely old) vanity link. Now, a hypixel hacker group as stolen your vanity link to sell alt Minecraft alt accounts. 

A detailed description of what actually happened.

**Expected Result:**
Take me to the trident support server.

A detailed description of what you expected to happen.

**Reproduction Steps:**
1. Open the website
2.  Click on the discord support server button

**Screenshot(s) or Video(s):**
N/A

**Comment by Dymidless** [comment]
We edited invite links a while ago, this is resolved.
