### ISSUE TITLE
moderate command not work correctly

### ISSUE THREAD

**Issue by Fiskemanden4321** [tridentdiscord/bugs#51]
**Discord User ID:** 351059273012215808
**Guild ID Affected:** 1254534918290018386
**Module/Command Affected:** /moderate 

A detailed description of the bug.   when i use /moderate when we come to the user everytime is put in a valid user its says  no results found 

**Actual Result:**
found out that the search do not work

A detailed description of what actually happened.
it should find  the user there are on roblox but it dont
**Expected Result:**

A detailed description of what you expected to happen.
it found the user 
**Reproduction Steps:**
1. /moderate user
2. no results 

**Screenshot(s) or Video(s):**
![image](https://github.com/user-attachments/assets/b789c4b2-be41-482c-ba93-aeb2cac9b1e2)

If applicable, attach screenshot(s) or video(s) to show the bug.

**Comment by Dymidless** [comment]
This is resolved.
