### ISSUE TITLE
LOA not submitting ended log or DMing for ended LOA.

### ISSUE THREAD

**Issue by CupCake8061** [tridentdiscord/bugs#6]
**Discord User ID:**745838125321814187
**Guild ID Affected:**817607800954945567
**Module/Command Affected:**LOA

A detailed description of the bug.
LOA ending for some does not show up in logging channel, Nor does the LOA Person get a DM regarding their LOA ending.
**Actual Result:**
LOA ending for some does not show up in logging channel, Nor does the LOA Person get a DM regarding their LOA ending.
A detailed description of what actually happened.
LOA did not show up, No warnings for ending LOA, No Logs of the LOA.
**Expected Result:**
Log of the ending LOA, DM sent to the Person.
A detailed description of what you expected to happen.
Log of the ending LOA, and ofcourse a DM sent to the person finishing LOA.
**Reproduction Steps:**
1. Start an LOA
2. Wait for ending

**Screenshot(s) or Video(s):**
![image](https://user-images.githubusercontent.com/123785461/216794982-61c9717a-6438-4dd3-b814-c93d1c570d95.png)
This shows no LOA ended on the time that the person's LOA ended.
![image](https://user-images.githubusercontent.com/123785461/216795013-fb46d4fe-fd4f-42bd-92d8-81bd89048067.png)

If applicable, attach screenshot(s) or video(s) to show the bug.

**Comment by Flqsh** [comment]
Archived
