### ISSUE TITLE
/help command

### ISSUE THREAD

**Issue by xInfinitxy** [tridentdiscord/bugs#7]
**Discord User ID:** 763388195261644811
**Guild ID Affected:** Global
**Module/Command Affected:** /help

A detailed description of the bug.

When using the /help command an error occurs, making the command not work. The error is "Application did not respond"

**Actual Result:**

A detailed description of what actually happened.
"Application did not respond" error occurred.

**Expected Result:**

A detailed description of what you expected to happen.
I expected for the /help message to appear.

**Reproduction Steps:**
1. Run /help in any server.
2. "Application didn't respond" error appears.

**Screenshot(s) or Video(s):**

If applicable, attach screenshot(s) or video(s) to show the bug.
![image](https://user-images.githubusercontent.com/124950220/218329253-d438587a-5846-41eb-a8ff-c263c0c3efa4.jpeg)

**Comment by whoissound** [comment]
Resolved.

**Comment by LostBreezely** [comment]
Note to self: Adjust fix at a later date.
