### ISSUE TITLE
Reminders Broken

### ISSUE THREAD

**Issue by finaIcutpro** [tridentdiscord/bugs#8]
**Discord User ID:** 459374864067723275
**Guild ID Affected:** 954835184900005990
**Module/Command Affected:** Reminders

The reminders **Done** button won't send.

**Actual Result:** It just doesn't work 💀

When I clicked "Done" - it recognized the response (doesn't time out). However, nothing happens. 

**Expected Result:**

I would expect the bot to work.

**Reproduction Steps:**
1.  Set up reminders
2. Click Done

**Screenshot(s) or Video(s):**
![Screenshot 2023-02-12 at 5 02 00 PM](https://user-images.githubusercontent.com/117038300/218345140-e035bcff-240c-4e25-a86f-8a74147a5a2a.jpg)

**Comment by Flqsh** [comment]
Cannot be reproduced - please send server ID

**Comment by finaIcutpro** [comment]
It works now.

**Comment by Flqsh** [comment]
Concluded
