### ISSUE TITLE
LOA Modal Bug

### ISSUE THREAD

**Issue by DiscordMax** [tridentdiscord/bugs#9]
**Discord User ID:**  493081244792520714
**Guild ID Affected:** 881570702975713300
**Module/Command Affected:** LOA System

A detailed description of the bug.
Modal fills with old Text from a previous LOA request I was going to deny but was denied before I could press submit. 
**Actual Result:** Modal fills with previous leave denied reasoning.

A detailed description of what actually happened.
I went to deny the leave request I sent and saw text from a previous leave I was going to deny in the reasoning.
**Expected Result:** Modal to be blank with no text.

A detailed description of what you expected to happen.

**Reproduction Steps:**
1. Create a Leave
2. Type reasoning deny the leave 'X' out of the modal
3. Someone else denies the leave before you
4. Create another leave
5. Press deny, the modal will still have text from the other one.

**Screenshot(s) or Video(s):**

If applicable, attach screenshot(s) or video(s) to show the bug.
[IMG_8077.png](https://cdn.discordapp.com/attachments/881573566951333929/1077040989501395104/IMG_8077.png)

**Comment by Flqsh** [comment]
This is not a bug. It's just the way Discord handles modals; we have no control over it.
